export const MOCK_ORDENS_SERVICO = [
  {
    OrdemServicoId: '0202260',
    Intervalo: 'SEMANAL',
    EquipamentoTipo: 'CAMINHÃO BAÚ',
    Tag: 'FTZ-227-002/SERV',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0362087',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA STORM',
    Tag: 'FTZ-018-001',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0362106',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA STORM',
    Tag: 'FTZ-018-002',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'NÃO OPERACIONAL',
  },
  {
    OrdemServicoId: '0362125',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA STORM',
    Tag: 'FTZ-018-003',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0362144',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA SPATE',
    Tag: 'FTZ-016-001',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0362163',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA SPATE',
    Tag: 'FTZ-016-004',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0362182',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA SPATE',
    Tag: 'FTZ-016-006',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0362202',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'EMPILHADEIRA YALE 2.5 TON',
    Tag: 'FTZ-086-002',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'NÃO OPERACIONAL',
  },
  {
    OrdemServicoId: '0371788',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'FERRAMENTAS',
    Tag: 'FTZ-000-017',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0371807',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA SUBMERSIVEL ALTA PERFORMANCE',
    Tag: 'FTZ-104-002',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0371826',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA SUBMERSIVEL ALTA PERFORMANCE',
    Tag: 'FTZ-104-001',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0371845',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA SPATE',
    Tag: 'FTZ-016-007',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0371864',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'MOTOBOMBA SPATE',
    Tag: 'FTZ-016-005',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0371884',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'EMPILHADEIRA 7,5 TON',
    Tag: 'FTZ-085-001',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
  {
    OrdemServicoId: '0371904',
    Intervalo: 'MENSAL',
    EquipamentoTipo: 'EMPILHADEIRA 2,5 TON',
    Tag: 'FTZ-086-001/SERV',
    DataProgramada: '2020-01-01',
    OrdemServicoStatus: 'PLANEJADA',
    EquipamentoStatus: 'OPERACIONAL',
  },
];
